In [4]:
import torch

word = torch.tensor([
    [1, 0, 0],   # "H" -> real letter
    [0, 1, 0],   # "i" -> real letter
    [0, 0, 0],   # padding
    [0, 0, 0],   # padding
])

print(word.sum(dim=1))          # tensor([1, 1, 0, 0])   <- sum per timestep
print(word.sum(dim=1) != 0)   # tensor([True, True, False, False])
print((word.sum(dim=1) != 0).sum())  # tensor(2)  <- real length = 2 ✅

tensor([1, 1, 0, 0])
tensor([ True,  True, False, False])
tensor(2)


In [8]:
word1 = torch.tensor([
    [1, 0, 0, 0, 0],   # "a"
    [0, 1, 0, 0, 0],   # "t"
    [0, 0, 0, 0, 0],   # padding
    [0, 0, 0, 0, 0],   # padding
])

# Word 2: "cat" -> 3 real letters, padded with 1 zero-vector
word2 = torch.tensor([
    [0, 0, 1, 0, 0],   # "c"
    [1, 0, 0, 0, 0],   # "a"
    [0, 0, 0, 1, 0],   # "t"
    [0, 0, 0, 0, 0],   # padding
])

# Word 3: "cats" -> 4 real letters, no padding needed
word3 = torch.tensor([
    [0, 0, 1, 0, 0],   # "c"
    [1, 0, 0, 0, 0],   # "a"
    [0, 0, 0, 1, 0],   # "t"
    [0, 0, 0, 0, 1],   # "s"
])

word4 = torch.stack([word1, word2, word3])


In [ ]:
print(word1.sum(dim=1))

tensor([1, 1, 0, 0])


In [9]:
word4.shape

torch.Size([3, 4, 5])

In [11]:
print(word4.sum(dim=2))

tensor([[1, 1, 0, 0],
        [1, 1, 1, 0],
        [1, 1, 1, 1]])


In [12]:
lengths = (word4.sum(dim=2) != 0).sum(dim=1)
print("lengths:", lengths)

lengths: tensor([2, 3, 4])
